name: 'Build Image'
description: 'Build Dockerfile within the github repo'
inputs:
  dockerfile_path:
    description: 'Declare path from root to the Dockerfile'
    required: true
    default: './Dockerfile'
  context:
    description: 'Declare contextual path from root to the proper directory'
    required: true
    default: '.'

runs:
  using: "composite"
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Docker Build Image
      run: |-
        docker buildx build --output type=docker,dest=/tmp/image.tar --tag base-image:latest --file ${{ inputs.dockerfile_path }} ${{ inputs.context }}
      shell: bash

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: image
        path: /tmp/image.tar
